name: Deploy

on:
  workflow_dispatch: 

jobs:
  deploy:
      name: ðŸš€ Deploy to environment
      runs-on: ubuntu-latest
      environment: ${{ inputs.env || 'development' }} 
      steps:
      - name: Print environment
        run: echo "Deploy to ${{ github.environment }}"
